---

- name: To install apache on ubuntu
  apt: name=apache2 state=present

- name: Install PHP
  apt: name=libapache2-mod-php state=present

- name: Install Hello World PHP Script
  copy: src=index.php dest=/var/www/html/index.php mode=0644

- name: Install Hello World PHP Script with database
  copy: src=db.php dest=/var/www/html/db.php mode=0644

- name: TO install phpMyAdmin
  apt: name=phpmyadmin state=present

- name: To configure site
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf

- name: To configure site 2
  copy: src=apache.conf dest=/etc/phpmyadmin/apache.conf
  notify:
    - apache_restart

- name: Restart apache
  service: name=apache2 state=restarted
