---
# tasks file for lamp
- name: To install lamp on Ubuntu
  include: "{{ item }}"
  with_items:
    - debian.yml
    - mysql.yml
  when:
    ansible_os_family == 'Debian'

- name: To install lamp on RedHat
  include: redhat.yml
  when:
    ansible_os_family == 'RedHat'

