---

- name: create database for wordpress
  mysql_db:
    name: wordpress
    state: present

- name: To upgrade mysql
  command: mysql_upgrade
  ignore_errors: yes
  tags:
    - db_upgrade

- name: To create db user
  mysql_user:
    name: wordpress
    password: "{{ db_password }}"
    priv: 'wordpress.*:ALL'
    state: present


